-- CREATE TABLE IFENG IP REPOSITORY.
CREATE EXTERNAL TABLE VDN_IP_REPO(IP STRING, ISP STRING, COUNTRY STRING, CITY STRING) PARTITIONED BY (DS STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' LOCATION 'hdfs://centos136.thinker.cn:8020/user/cloudland/vdn/all'; 
CREATE EXTERNAL TABLE VDN_IP_REPO_CN(IP STRING, ISP STRING, COUNTRY STRING, CITY STRING) PARTITIONED BY (DS STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' LOCATION 'hdfs://centos136.thinker.cn:8020/user/cloudland/vdn/CN'; 
CREATE EXTERNAL TABLE VDN_IP_REPO_US(IP STRING, ISP STRING, COUNTRY STRING, CITY STRING) PARTITIONED BY (DS STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' LOCATION 'hdfs://centos136.thinker.cn:8020/user/cloudland/vdn/US'; 
CREATE EXTERNAL TABLE VDN_IP_REPO_CAN(IP STRING, ISP STRING, COUNTRY STRING, CITY STRING) PARTITIONED BY (DS STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' LOCATION 'hdfs://centos136.thinker.cn:8020/user/cloudland/vdn/CAN'; 

