-- CREATE TABLES;

-- CREATE VDN_LOGS TABLE (FOR VID='vNsPlayer_nsvp1.0.18'):
CREATE EXTERNAL TABLE VDN_LOGS( ERR STRING, IP STRING, REF STRING, SID STRING, UID STRING, LOC STRING, CAT STRING, TM STRING, URL STRING, DUR INT, BT INT, BL INT, LT INT, VID STRING, PTYPE STRING, CDNID STRING, NETNAME STRING, TR STRING ) PARTITIONED BY (DS STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' LOCATION 'hdfs://ubuntu144.thinker.cn:9000/user/cloudland/vdnlogs/VDN_LOGS/'; 

-- CREATE VDN_LOGS TABLE 
CREATE EXTERNAL TABLE VDN_LOGS_FULLY( ERR STRING, IP STRING, REF STRING, SID STRING, UID STRING, LOC STRING, CAT STRING, TM STRING, URL STRING, DUR INT, BT INT, BL INT, LT INT, VID STRING, PTYPE STRING,  CDNID STRING, NETNAME STRING, TR STRING, ISP STRING , COUNTRY STRING, CITY STRING) PARTITIONED BY (DS STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' LOCATION 'hdfs://ubuntu144.thinker.cn:9000/user/cloudland/vdnlogs/VDN_LOGS_FULLY/'; 

-- CREATE TABLE VDN_LOGS_OTHER (FOR LOC NOT IN VDN_IP_REPO)
CREATE EXTERNAL TABLE VDN_LOGS_OTHER( ERR STRING, IP STRING, REF STRING, SID STRING, UID STRING, LOC STRING, CAT STRING, TM STRING, URL STRING, DUR INT, BT INT, BL INT, LT INT, VID STRING, PTYPE STRING,  CDNID STRING, NETNAME STRING, TR STRING ) PARTITIONED BY (DS STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' LOCATION 'hdfs://ubuntu144.thinker.cn:9000/user/cloudland/vdnlogs/VDN_LOGS_OTHER/'; 

-- CREATE TABLE VDN_LOGS_IFENG (FOR LOC IN VDN_IP_REPO)
CREATE EXTERNAL TABLE VDN_LOGS_IFENG( ERR STRING, IP STRING, REF STRING, SID STRING, UID STRING, LOC STRING, CAT STRING, TM STRING, URL STRING, DUR INT, BT INT, BL INT, LT INT, VID STRING, PTYPE STRING,  CDNID STRING, NETNAME STRING, TR STRING ) PARTITIONED BY (DS STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' LOCATION 'hdfs://ubuntu144.thinker.cn:9000/user/cloudland/vdnlogs/VDN_LOGS_IFENG/'; 

-- CREATE TABLE VDN_GROUP_BY_ERR FOR GROUP BY ERR RESULTS;
CREATE TABLE VDN_GROUP_BY_ERR (ERR STRING, TOTAL INT, CT STRING, TR STRING, ORIGIN STRING) PARTITIONED BY (DS STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'; 

-- CREATE TABLE VDN_IP_REPO`
CREATE TABLE VDN_NODE_REPO(IP STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t';

-- CREATE TABLE IP AUDIT DAILY REPORT

-- CREATE TABLE 
CREATE TABLE VDN_AVLB_DAILY(ERR STRING, TOTAL INT, CT STRING) PARTITIONED BY (DS STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'; 

-- CREATE TABLE VDN_AVLB_MINUTELY
CREATE EXTERNAL TABLE VDN_AVLB_MINUTELY(ERR STRING, TOTAL INT, CT STRING, TR STRING) PARTITIONED BY (DS STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' LOCATION 'hdfs://ubuntu144.thinker.cn:9000/user/cloudland/vdnlogs/VDN_AVLB_MINUTELY/';


-- CREATE TABLE VDN_AVLB_MINUTELY_FULLY
CREATE EXTERNAL TABLE VDN_AVLB_MINUTELY_FULLY(ERR STRING, TOTAL INT,  ISP STRING, COUNTRY STRING, CITY STRING, CT STRING, TR STRING, CAT STRING) PARTITIONED BY (DS STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' LOCATION 'hdfs://ubuntu144.thinker.cn:9000/user/cloudland/vdnlogs/VDN_AVLB_MINUTELY_FULLY';

-- CREATE TABLE VDN_AVLB_MINUTELY_FULLY_GATHER
CREATE EXTERNAL TABLE VDN_AVLB_MINUTELY_FULLY_GATHER (ERR STRING, TOTAL INT,  ISP STRING, COUNTRY STRING, CT STRING, TR STRING, CAT STRING) PARTITIONED BY (DS STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' LOCATION 'hdfs://ubuntu144.thinker.cn:9000/user/cloudland/vdnlogs/VDN_AVLB_MINUTELY_FULLY_GATHER';

-- CREATE TABLE VDN_AVLB_MINUTELY_FULLY_REPORT
CREATE EXTERNAL TABLE VDN_AVLB_MINUTELY_FULLY_REPORT(ISP STRING, CT STRING, TR STRING, CAT STRING, A INT, B INT, C INT, C2 INT, C3 INT, C4 INT, D INT, D2 INT, D3 INT, E INT, F INT, F2 INT, G INT, G2 INT) PARTITIONED BY (DS STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' LOCATION 'hdfs://ubuntu144.thinker.cn:9000/user/cloudland/vdnlogs/VDN_AVLB_MINUTELY_FULLY_REPORT';

-- CREATE TABLE VDN_AVLB_MINUTEL_REPORT
CREATE TABLE VDN_AVLB_MINUTELY_REPORT(NUMERATOR INT, DENOMINATOR INT, CT STRING, TR STRING, AVLB DECIMAL(6, 5)) PARTITIONED BY (DS STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'; 

-- CREATE TABLE VDN_FLUENT_MINUTEL_REPORT
CREATE TABLE VDN_FLUENT_MINUTEL_REPORT(T0 INT, T1 INT, T2 INT, T3 INT, T4 INT, TR STRING, CT STRING) PARTITIONED BY (DS STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'; 


