-- DROP TABLES
-- CREATE VDN_LOGS TABLE (FOR VID='vNsPlayer_nsvp1.0.18'):
DROP TABLE VDN_LOGS_FULLY; 

DROP TABLE VDN_LOGS_OTHER; 

DROP TABLE VDN_LOGS_IFENG; 

DROP TABLE VDN_AVLB_MINUTELY;

DROP TABLE VDN_AVLB_MINUTELY_FULLY;

DROP TABLE VDN_GROUP_BY_ERR;

DROP TABLE vdn_avlb_daily;

DROP TABLE vdn_avlb_minutely_report;

DROP TABLE vdn_fluent_minutel_report;

