-- CREATE TABLE IFENG IP REPOSITORY.
CREATE EXTERNAL TABLE VDN_IP_REPO(IP STRING, COUNTRY STRING, CITY STRING, ISP STRING) PARTITIONED BY (DS STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' LOCATION 'hdfs://centos136.thinker.cn:8020/user/cloudland/vdn'; 
CREATE EXTERNAL TABLE VDN_IP_REPO_CN(IP STRING, COUNTRY STRING, CITY STRING, ISP STRING) PARTITIONED BY (DS STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' LOCATION 'hdfs://centos136.thinker.cn:8020/user/cloudland/vdn'; 
CREATE EXTERNAL TABLE VDN_IP_REPO_US(IP STRING, COUNTRY STRING, CITY STRING, ISP STRING) PARTITIONED BY (DS STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' LOCATION 'hdfs://centos136.thinker.cn:8020/user/cloudland/vdn'; 
CREATE EXTERNAL TABLE VDN_IP_REPO_CAN(IP STRING, COUNTRY STRING, CITY STRING, ISP STRING) PARTITIONED BY (DS STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' LOCATION 'hdfs://centos136.thinker.cn:8020/user/cloudland/vdn'; 



-- LOAD DATA INTO TABLE VDN_IP_REPO
#LOAD DATA INPATH 'hdfs://centos136.thinker.cn:8020/user/cloudland/iparea/output/part-r-00000' INTO TABLE VDN_IP_REPO PARTITION (ds ='2015-07-18');
LOAD DATA INPATH 'hdfs://centos136.thinker.cn:8020/user/cloudland/iparea/CN/output/part-r-00000' INTO TABLE VDN_IP_REPO_CN PARTITION (ds ='2015-07-18');
LOAD DATA INPATH 'hdfs://centos136.thinker.cn:8020/user/cloudland/iparea/US/output/part-r-00000' INTO TABLE VDN_IP_REPO_US PARTITION (ds ='2015-07-18');
LOAD DATA INPATH 'hdfs://centos136.thinker.cn:8020/user/cloudland/iparea/CAN/output/part-r-00000' INTO TABLE VDN_IP_REPO_CAN PARTITION (ds ='2015-07-18');

