-- DROP TABLES
-- CREATE VDN_LOGS TABLE (FOR VID='vNsPlayer_nsvp1.0.18'):
DROP TABLE VDN_LOGS; 

DROP TABLE VDN_LOGS_OTHER; 

DROP TABLE VDN_LOGS_IFENG; 

DROP TABLE GROUP_BY_ERR; 

DROP TABLE VDN_IP_REPO;

DROP TABLE VDN_IP_GROUP_DAILY;
