-- CREATE TABLES;

-- CREATE VDN_LOGS TABLE (FOR VID='vNsPlayer_nsvp1.0.18'):
CREATE EXTERNAL TABLE VDN_LOGS( ERR STRING, IP STRING, REF STRING, SID STRING, UID STRING, LOC STRING, TM STRING, URL STRING, DUR INT, BT INT, BL INT, LT INT, VID STRING, CDNID STRING, NETNAME STRING, KEY STRING, CT STRING ) PARTITIONED BY (DS STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' LOCATION 'hdfs://centos136.thinker.cn:8020/user/cloudland/output/'; 

-- CREATE TABLE VDN_LOGS_OTHER (FOR LOC NOT IN VDN_IP_REPO)
CREATE TABLE VDN_LOGS_OTHER( ERR STRING, IP STRING, REF STRING, SID STRING, UID STRING, LOC STRING, TM STRING, URL STRING, DUR INT, BT INT, BL INT, LT INT, VID STRING, CDNID STRING, NETNAME STRING, KEY STRING, CT STRING ) PARTITIONED BY (DS STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'; 

-- CREATE TABLE VDN_LOGS_OTHER (FOR LOC IN VDN_IP_REPO)
CREATE TABLE VDN_LOGS_IFENG( ERR STRING, IP STRING, REF STRING, SID STRING, UID STRING, LOC STRING, TM STRING, URL STRING, DUR INT, BT INT, BL INT, LT INT, VID STRING, CDNID STRING, NETNAME STRING, KEY STRING, CT STRING ) PARTITIONED BY (DS STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'; 

-- CREATE TABLE GROUP_BY_ERR FOR GROUP BY ERR RESULTS;
CREATE TABLE GROUP_BY_ERR (ERR STRING, TOTAL INT, CT STRING, ORIGIN STRING) PARTITIONED BY (DS STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'; 

-- CREATE TABLE VDN_IP_REPO
CREATE TABLE VDN_IP_REPO(IP STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t';

-- CREATE TABLE VDN_IP_GROUP_DAILY
CREATE EXTERNAL TABLE VDN_IP_GROUP_DAILY (IP STRING, TOTAL INT) PARTITIONED BY (DS STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' LOCATION '/user/cloudland/vdnlogs/output/';
